### ISSUE TITLE
I can't setup multi project

### ISSUE THREAD

**Issue by gabrielsestrem** [supabase/supabase-grafana#13]
## Describe the bug

I can't use multiproject with this repository

## To Reproduce

In the file entrypoint.sh line 5 there's this code:

`if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then`

this will lead to single project monitoring, if I have SUPABASE_ACESS_TOKEN. I had to populate `SUPABASE_ACCESS_TOKEN` to monitor multiple projects. So it does not goes into the 'else' in line 22.

**Comment by encima** [comment]
Thanks for this, we will update the README to make this clearer. For multi project monitoring, you only need to set the project ref and service role key.

In bash, the `-z` check is checking for an empty string so it will go to the `else` when it is unset or set to nothing.
