### ISSUE TITLE
First deploy fail 

### ISSUE THREAD

**Issue by riderx** [supabase/supabase-grafana#2]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
The cli ask question they are not documented, and make weird change depending what you select.

![CleanShot 2023-11-29 at 17 59 23@2x](https://github.com/supabase/supabase-grafana/assets/4084527/a0dd8ad2-6a60-4836-8344-5b0c2c3ddd79)

![CleanShot 2023-11-29 at 18 01 28@2x](https://github.com/supabase/supabase-grafana/assets/4084527/d7d365a9-31b1-4b51-9eb5-c0134a800228)

![CleanShot 2023-11-29 at 18 00 58@2x](https://github.com/supabase/supabase-grafana/assets/4084527/ce5b704f-3f17-4cfd-84b4-b9741a7be51a)

## To Reproduce

follow the README tutorial.

## Expected behavior

This should be documented, what to answer to the CLI

**Comment by pcnc** [comment]
Hi Martin - thanks for the report!
We'll take a closer look at this to document the exact steps required to be executed and help streamline the process.

**Comment by encima** [comment]
Closing as this is fixed by #3.

**Comment by riderx** [comment]
Thanks, I have used the new setup since February and its works like a charm
